2017-05-10 11:49:03 database: wrong user or password; user: "MATTIA"
org.h2.message.DbException: Wrong user name or password [28000-194]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 9 more
2017-05-25 15:08:08 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 13 more
2017-05-25 15:08:13 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 13 more
2017-05-26 11:21:32 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 13 more
06-01 11:46:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('dfrrd','lkjh@ljk.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('dfrrd','lkjh@ljk.it','questa' [42001-182]
06-01 11:46:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('dfrrd','lkjh@ljk.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('dfrrd','lkjh@ljk.it','questa' [42001-182]
06-01 11:47:28 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('qwert','xcv@po.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('qwert','xcv@po.it','questa' [42001-182]
06-01 11:51:02 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('qwertyu','dxcv@lip.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('qwertyu','dxcv@lip.it','questa' [42001-182]
06-01 12:05:51 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('asdfg','ert@poiu.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('asdfg','ert@poiu.it','questa' [42001-182]
06-01 12:05:56 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('asdfg','ert@poiu.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('asdfg','ert@poiu.it','questa' [42001-182]
06-01 12:05:58 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('asdfg','ert@poiu.it','questa'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('asdfg','ert@poiu.it','questa' [42001-182]
06-06 23:01:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-06 23:02:34 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-06 23:13:42 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('prova2','prova2@prova.it','prova'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('prova2','prova2@prova.it','prova' [42001-182]
06-06 23:18:27 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('prova2','prova2@prova.it','prova'[*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO UTENTE (NOMEUTENTE, EMAIL, PASSWORD) VALUES ('prova2','prova2@prova.it','prova' [42001-182]
06-06 23:37:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-06 23:44:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-07 09:54:55 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: View "PROVACARTETERRITORIOPARTITA" already exists; SQL statement:
CREATE VIEW PROVACARTETERRITORIOPARTITA AS (SELECT * FROM CARTATERRITORIO ORDER BY RAND()) [90038-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateView.update(CreateView.java:85)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at server.element.Partita.<init>(Partita.java:53)
	at server.StartServer.addGame(StartServer.java:124)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-07 23:53:27 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "VIEW"; SQL statement:
DELETE TOP 1 FROM PROVACARTETERRITORIOPARTITA [50100-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.table.TableView.removeRow(TableView.java:351)
	at org.h2.command.dml.Delete.update(Delete.java:94)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:130)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:115)
	at server.element.Partita.setCards(Partita.java:261)
	at server.StartServer.setCards(StartServer.java:175)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:160)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-07 23:56:12 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "VIEW"; SQL statement:
DELETE TOP 1 FROM PROTACARTETERRITORIOPARTITA [50100-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.table.TableView.removeRow(TableView.java:351)
	at org.h2.command.dml.Delete.update(Delete.java:94)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:130)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:115)
	at server.element.Partita.setCards(Partita.java:261)
	at server.StartServer.setCards(StartServer.java:175)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:160)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-08 11:19:23 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Column "EFFETTOIMMEDIATO3" not found [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3120)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at server.element.CartaSviluppo.setCarta(CartaSviluppo.java:48)
	at server.element.Partita.setCards(Partita.java:260)
	at server.StartServer.setCards(StartServer.java:175)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:160)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-08 11:19:23 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "VIEW"; SQL statement:
DELETE TOP 1 FROM PROVACARTETERRITORIOPARTITA [50100-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.table.TableView.removeRow(TableView.java:351)
	at org.h2.command.dml.Delete.update(Delete.java:94)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:130)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:115)
	at server.element.Partita.setCards(Partita.java:262)
	at server.StartServer.setCards(StartServer.java:175)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:160)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-08 12:33:23 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "PERODO" not found; SQL statement:
CREATE TABLE PROVACARTETERRITORIOPARTITA AS SELECT * FROM PROVACARTETERRITORIOPARTITARANDOM ORDER BY PERODO [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Select.prepare(Select.java:829)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at server.element.Partita.<init>(Partita.java:61)
	at server.StartServer.addGame(StartServer.java:126)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:47)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:160)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-08 12:34:52 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Table "PROVACARTETERRITORIOPARTITARANDOM" already exists; SQL statement:
CREATE TABLE PROVACARTETERRITORIOPARTITARANDOM AS SELECT * FROM CARTATERRITORIO ORDER BY RAND() [42101-182]
06-08 14:56:35 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "PROVACARTETERRITORIOPARTITARANDOM" already exists; SQL statement:
CREATE TABLE PROVACARTETERRITORIOPARTITARANDOM AS SELECT * FROM CARTATERRITORIO ORDER BY RAND() [42101-182]
06-08 14:57:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE CACCACARTEEDIFICIO PARTITARANDOM[*]"; SQL statement:
DROP TABLE CACCACARTEEDIFICIO PARTITARANDOM [42000-182]
06-08 17:10:46 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE VOGLIACARTEEDIFICIO PARTITARANDOM[*]"; SQL statement:
DROP TABLE VOGLIACARTEEDIFICIO PARTITARANDOM [42000-182]
06-08 17:14:27 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
DROP TABLE VERDECARTETERRITORIOPARTITARANDOM [90002-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Prepared.query(Prepared.java:212)
	at org.h2.command.CommandContainer.query(CommandContainer.java:90)
	at org.h2.command.Command.executeQuery(Command.java:197)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:79)
	at server.element.Partita.<init>(Partita.java:72)
	at server.StartServer.addGame(StartServer.java:127)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:47)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-15 15:41:40 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Column "WHITE" not found; SQL statement:
SELECT IMMAGINE FROM BANDIERA WHERE COLORE = white [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:832)
	at org.h2.command.Parser.prepareCommand(Parser.java:247)
	at org.h2.engine.Session.prepareLocal(Session.java:446)
	at org.h2.engine.Session.prepareCommand(Session.java:388)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1190)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:73)
	at server.element.Flag.setFlagImage(Flag.java:53)
	at server.element.Flag.<init>(Flag.java:31)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017-06-15 15:43:36 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 13 more
2017-06-15 15:43:42 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 13 more
06-15 16:11:33 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-15 16:14:03 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-15 16:17:43 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-182]
06-17 13:46:23 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "EFFETTOIMMEDIATO1" not found [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3120)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at server.element.CartaPersonaggi.setCarta(CartaPersonaggi.java:50)
	at server.element.Partita.setCards(Partita.java:359)
	at server.StartServer.setCards(StartServer.java:177)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-17 13:46:23 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "EFFETTOIMMEDIATO1" not found [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3120)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at server.element.CartaPersonaggi.setCarta(CartaPersonaggi.java:50)
	at server.element.Partita.setCards(Partita.java:359)
	at server.StartServer.setCards(StartServer.java:177)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-17 13:46:23 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "EFFETTOIMMEDIATO1" not found [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3120)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at server.element.CartaPersonaggi.setCarta(CartaPersonaggi.java:50)
	at server.element.Partita.setCards(Partita.java:359)
	at server.StartServer.setCards(StartServer.java:177)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
06-17 13:46:23 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "EFFETTOIMMEDIATO1" not found [42122-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3120)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3208)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:302)
	at server.element.CartaPersonaggi.setCarta(CartaPersonaggi.java:50)
	at server.element.Partita.setCards(Partita.java:359)
	at server.StartServer.setCards(StartServer.java:177)
	at server.ImplementServerInterface.createNewLobby(ImplementServerInterface.java:48)
	at server.ThreadSocketServer.run(ThreadSocketServer.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017-06-17 13:46:57 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:148)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 18 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/parke/test.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 13 more
